my_list = [
[
"I assess the potential consequences of not completing the task.1",
"I choose tasks based on their complexity and my current mood.2",
"I consider the task's long-term impact on my goals.3",
"I prioritize based on deadlines given by others.4",
],
[
"I often end up reacting to urgent tasks as they come up.1",
"I delegate urgent tasks that are less important.2",
"I allocate specific time slots for urgent tasks and stick to them.3",
"I review and adjust my schedule daily to manage urgent tasks.4",
],
[
"I often get sidetracked by such tasks and lose focus on long-term goals.1",
"I evaluate their necessity before proceeding.2",
"I quickly assess and delegate them if possible.3",
"I handle them as efficiently as possible to get back to my main goals.4",
],
[
"I often struggle to find a balance between the two.1",
"I handle urgent tasks immediately and revisit important tasks later.2",
"I try to balance both by interspersing them throughout my day.3",
"I complete important and urgent tasks first and schedule time for the others.4",
],
[
"I rely on deadlines and the perceived urgency.1",
"I use the Eisenhower Matrix to categorize and prioritize tasks.2",
"I often tackle tasks that seem easier to complete first.3",
"I focus on tasks that will have the most immediate impact.4",
],
[
"I often pick leisure activities based on convenience.1",
"I choose activities that relax and rejuvenate me.2",
"I prioritize activities that align with my personal interests and goals.3",
"I schedule a variety of leisure activities to balance enjoyment and benefit.4",
],
[
"I often let work encroach on my personal time.1",
"I ensure personal time is scheduled in my daily routine.2",
"I set strict boundaries between work and personal time.3",
"I adjust my schedule daily based on workload.4",
],
[
"I often push through until all tasks are done, risking burnout.1",
"I take regular breaks and practice self-care.2",
"I delegate or seek support for some urgent tasks.3",
"I prioritize and manage my workload to avoid overload.4",
],
[
"I often find it hard to make time for long-term planning.1",
"I integrate long-term planning into my weekly review sessions.2",
"I allocate specific times for urgent tasks and separate times for planning.3",
"I handle urgent tasks first and fit in planning when possible.4",
],
[
"I often overlook sustainability due to a busy schedule.1",
"I choose eco-friendly activities and practices.2",
"I educate myself about sustainability and apply what I learn.3",
"I prioritize activities that reduce my environmental impact.4",
],
[
"I rarely assess my time estimates systematically.1",
"I seek feedback on my time management from peers.2",
"I compare actual time taken with my initial estimates.3",
"I review my time logs and adjust my future estimates.4",
],
[
"I often get caught up in urgent tasks at the expense of important ones.1",
"I schedule dedicated time for important tasks regardless of urgency.2",
"I regularly review and adjust my priorities.3",
"I use reminders to keep important tasks on my radar.4",
],
[
"I often feel stressed and behind schedule.1",
"I extend my work hours to complete them.2",
"I seek additional resources or help to speed up completion.3",
"I reassess their importance and adjust other tasks accordingly.4",
],
[
"I often focus more on immediate tasks and neglect strategic planning.1",
"I dedicate specific times for strategic planning.2",
"I set clear milestones and review progress regularly.3",
"I ensure daily tasks align with strategic goals.4",
],
[
"I rarely evaluate my productivity systematically. 1",
"I compare my results to my initial plans and adjust.2",
"I seek feedback and use productivity tools.3",
"I reflect on my accomplishments and set improvement goals.4",
],
[
"I often struggle to identify the root causes.1",
"I use motivational techniques to get started.2",
"I reflect on my motivations and barriers regularly.3",
"I break down tasks into smaller, more manageable parts.4",
],
[
"I often get distracted by digital interruptions.1",
"I designate specific times for checking emails and messages.4",
"I create a focused work environment.3",
"I use apps to block distracting websites and notifications.2",
],
[
"I often struggle to maintain motivation for long-term projects.1",
"I seek inspiration and motivation from external sources.2",
"I regularly remind myself of the long-term benefits.3",
"I set mini-goals and celebrate small victories.4",
],
[
"I often feel paralyzed and unable to start.1",
"I take short breaks to clear my mind and refocus.2",
"I seek help or delegate tasks when possible.3",
"I prioritize and focus on one task at a time.4",
],
[
"I often neglect mindfulness practices due to a busy schedule.1",
"I take mindful breaks throughout the day.2",
"I engage in activities like yoga to promote mindfulness.3",
"I practice mindfulness techniques such as meditation daily.4",
],
]
